[manager]
show_hidden = true

[opener]
play = [
  { run = "mpv %*", ophran = true, for = "windows" },
]
edit = [
  { run = "nvim %*", block = true, for = "windows" },
]
open = [
  { run = "%*", ophran = true, for = "windows"},
]

[open]
prepend_rules = [
	{ name = "*.json", use = ["open", "edit"] },
]
